### YamlMime:PowershellCmdlet
summary: |-
  > [!TIP]
  > We encourage you to make improvements to this documentation. Please navigate to https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPSearchSettings.md to change this file.

  Sets search settings for a site
module: PnP.Powershell
links:
- text: Microsoft 365 Patterns and Practices
  href: https://aka.ms/m365pnp
syntaxes:
- >-
  Set-PnPSearchSettings [-SearchBoxInNavBar <SearchBoxInNavBarType>] [-SearchPageUrl <String>]

   [-SearchBoxPlaceholderText <String>] [-SearchScope <SearchScopeType>] [-Scope <SearchSettingsScope>] [-Force]

   [-Connection <PnPConnection>] [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    Set-PnPSearchSettings -SearchBoxInNavBar Hidden -Scope Site
  description: |-
    Hide the suite bar search box on all pages and sites in the site collection
  summary: ""
- title: EXAMPLE 2
  code: |-
    Set-PnPSearchSettings -SearchBoxInNavBar Hidden -Scope Web
  description: |-
    Hide the suite bar search box on all pages in the current site
  summary: ""
- title: EXAMPLE 3
  code: |-
    Set-PnPSearchSettings -SearchPageUrl "https://contoso.sharepoint.com/sites/mysearch/SitePages/search.aspx"
  description: |-
    Redirect the suite bar search box in the site to a custom URL
  summary: ""
- title: EXAMPLE 4
  code: |-
    Set-PnPSearchSettings -SearchPageUrl ""
  description: |-
    Clear the suite bar search box URL and revert to the default behavior
  summary: ""
- title: EXAMPLE 5
  code: |-
    Set-PnPSearchSettings -SearchPageUrl "https://contoso.sharepoint.com/sites/mysearch/SitePages/search.aspx" -Scope Site
  description: |-
    Redirect classic search to a custom URL
  summary: ""
- title: EXAMPLE 6
  code: |-
    Set-PnPSearchSettings -SearchScope Tenant
  description: |-
    Set default behavior of the suite bar search box to show tenant wide results instead of site or hub scoped results
  summary: ""
- title: EXAMPLE 7
  code: |-
    Set-PnPSearchSettings -SearchScope Hub
  description: |-
    Set default behavior of the suite bar search box to show hub results instead of site results on an associated hub site
  summary: ""
parameters:
- type: <xref href="PnPConnection" data-throw-if-not-resolved="False" />
  name: Connection
  description: |+
    Optional connection to be used by the cmdlet. Retrieve the value for this parameter by either specifying -ReturnConnection on Connect-PnPOnline or by executing Get-PnPConnection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Do not ask for confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SearchSettingsScope" data-throw-if-not-resolved="False" />
  name: Scope
  description: |+
    Scope to apply the setting to. Possible values: Web (default), Site\r\n\r\nFor a root site, the scope does not matter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Site, Web
- type: <xref href="SearchBoxInNavBarType" data-throw-if-not-resolved="False" />
  name: SearchBoxInNavBar
  description: |+
    Set the scope of which the suite bar search box shows. Possible values: Inherit, AllPages, ModernOnly, Hidden

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Inherit, AllPages, ModernOnly, Hidden
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchBoxPlaceholderText
  description: |+
    {{ Fill SearchBoxPlaceholderText Description }}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchPageUrl
  description: |+
    Set the URL where the search box should redirect to.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SearchScopeType" data-throw-if-not-resolved="False" />
  name: SearchScope
  description: |+
    Set the search scope of the suite bar search box. Possible values: DefaultScope, Tenant, Hub, Site

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: DefaultScope, Tenant, Hub, Site
applicable:
- SharePoint Online
uid: PnP.Powershell.Set-PnPSearchSettings
name: Set-PnPSearchSettings
description: ""
metadata:
  Module Name: PnP.PowerShell
  title: Set-PnPSearchSettings
  schema: 2.0.0
  applicable: SharePoint Online
  external help file: PnP.PowerShell.dll-Help.xml
  online version: https://pnp.github.io/powershell/cmdlets/Set-PnPSearchSettings.html
