### YamlMime:PowershellCmdlet
summary: |-
  > [!TIP]
  > We encourage you to make improvements to this documentation. Please navigate to https://github.com/pnp/powershell/blob/dev/documentation/Set-PnPSearchConfiguration.md to change this file.

  Sets the search configuration
module: PnP.Powershell
links:
- text: Microsoft 365 Patterns and Practices
  href: https://aka.ms/m365pnp
syntaxes:
- >-
  Set-PnPSearchConfiguration -Configuration <String> [-Scope <SearchConfigurationScope>] 

   [-Connection <PnPConnection>] [<CommonParameters>]
- >-
  Set-PnPSearchConfiguration -Path <String> [-Scope <SearchConfigurationScope>] 

   [-Connection <PnPConnection>] [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    Set-PnPSearchConfiguration -Configuration $config
  description: |-
    Sets the search configuration for the current web
  summary: ""
- title: EXAMPLE 2
  code: |-
    Set-PnPSearchConfiguration -Configuration $config -Scope Site
  description: |-
    Sets the search configuration for the current site collection
  summary: ""
- title: EXAMPLE 3
  code: |-
    Set-PnPSearchConfiguration -Configuration $config -Scope Subscription
  description: |-
    Sets the search configuration for the current tenant
  summary: ""
- title: EXAMPLE 4
  code: |-
    Set-PnPSearchConfiguration -Path searchconfig.xml -Scope Subscription
  description: |-
    Reads the search configuration from the specified XML file and sets it for the current tenant
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Configuration
  isRequired: true
  description: |+
    Search configuration string

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PnPConnection" data-throw-if-not-resolved="False" />
  name: Connection
  description: |+
    Optional connection to be used by the cmdlet. Retrieve the value for this parameter by either specifying -ReturnConnection on Connect-PnPOnline or by executing Get-PnPConnection.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Path
  isRequired: true
  description: |+
    Path to a search configuration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SearchConfigurationScope" data-throw-if-not-resolved="False" />
  name: Scope
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Web, Site, Subscription
applicable:
- SharePoint Online
uid: PnP.Powershell.Set-PnPSearchConfiguration
name: Set-PnPSearchConfiguration
description: ""
metadata:
  Module Name: PnP.PowerShell
  title: Set-PnPSearchConfiguration
  schema: 2.0.0
  applicable: SharePoint Online
  external help file: PnP.PowerShell.dll-Help.xml
  online version: https://pnp.github.io/powershell/cmdlets/Set-PnPSearchConfiguration.html
