### YamlMime:PowershellCmdlet
summary: |-
  Creates a new ContentEnrichmentConfiguration object.
module: sharepoint-server
notes: ""
links:
- text: Get-SPEnterpriseSearchContentEnrichmentConfiguration
  href: Get-SPEnterpriseSearchContentEnrichmentConfiguration.yml
- text: Set-SPEnterpriseSearchContentEnrichmentConfiguration
  href: Set-SPEnterpriseSearchContentEnrichmentConfiguration.yml
- text: Remove-SPEnterpriseSearchContentEnrichmentConfiguration
  href: Remove-SPEnterpriseSearchContentEnrichmentConfiguration.yml
syntaxes:
- >-
  New-SPEnterpriseSearchContentEnrichmentConfiguration [-AssignmentCollection <SPAssignmentCollection>]

   [<CommonParameters>]
examples:
- title: '------------------EXAMPLE------------------'
  code: |-
    $config = New-SPEnterpriseSearchContentEnrichmentConfiguration
  description: |-
    This example creates a new ContentEnrichmentConfiguration object.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal.
    Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management.
    Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory.
    When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store.
    If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server Subscription Edition
  parameterValueGroup: ""
applicable:
- SharePoint Server Subscription Edition
uid: sharepoint-server.New-SPEnterpriseSearchContentEnrichmentConfiguration
name: New-SPEnterpriseSearchContentEnrichmentConfiguration
description: |-
  This cmdlet creates a new ContentEnrichmentConfiguration object that the user can change.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://docs.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  module name: SharePointServer
  online version: https://docs.microsoft.com/powershell/module/sharepoint-server/new-spenterprisesearchcontentenrichmentconfiguration
  applicable: SharePoint Server Subscription Edition
  title: New-SPEnterpriseSearchContentEnrichmentConfiguration
  schema: 2.0.0
