### YamlMime:PowershellCmdlet
summary: |-
  Removes the current content enrichment configuration from the search service application.
module: SharePointServer
notes: ""
links:
- text: Get-SPEnterpriseSearchContentEnrichmentConfiguration
  href: Get-SPEnterpriseSearchContentEnrichmentConfiguration.yml
- text: Set-SPEnterpriseSearchContentEnrichmentConfiguration
  href: Set-SPEnterpriseSearchContentEnrichmentConfiguration.yml
- text: New-SPEnterpriseSearchContentEnrichmentConfiguration
  href: New-SPEnterpriseSearchContentEnrichmentConfiguration.yml
syntaxes:
- >-
  Remove-SPEnterpriseSearchContentEnrichmentConfiguration -SearchApplication <SearchServiceApplicationPipeBind>

   [-AssignmentCollection <SPAssignmentCollection>] [<CommonParameters>]
examples:
- title: '------------------EXAMPLE-----------------'
  code: |-
    $ssa = Get-SPEnterpriseSearchServiceApplication
    Remove-SPEnterpriseSearchContentEnrichmentConfiguration -SearchApplication $ssa
  description: |-
    This example removes the content enrichment configuration from the default search service application.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SearchServiceApplicationPipeBind" data-throw-if-not-resolved="False" />
  name: SearchApplication
  isRequired: true
  description: |+
    Specifies the SearchServiceApplication that contains content enrichment configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Remove-SPEnterpriseSearchContentEnrichmentConfiguration
name: Remove-SPEnterpriseSearchContentEnrichmentConfiguration
description: |-
  This cmdlet removes the current content enrichment configuration from the SearchServiceApplication.

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://docs.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.Search.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://docs.microsoft.com/powershell/module/sharepoint-server/remove-spenterprisesearchcontentenrichmentconfiguration
  applicable: SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Remove-SPEnterpriseSearchContentEnrichmentConfiguration
  schema: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
