### YamlMime:PowershellCmdlet
summary: |-
  Sets permission and identity information.
module: SharePointServer
notes: ""
syntaxes:
- >-
  Set-SPProfileServiceApplicationSecurity -Identity <SPObjectSecurity>

   -ProfileServiceApplicationProxy <SPServiceApplicationProxyPipeBind>

   [-AssignmentCollection <SPAssignmentCollection>] [-Confirm] [-SiteSubscription <SPSiteSubscriptionPipeBind>]

   [-Type <String>] [-WhatIf] [<CommonParameters>]
examples:
- title: '--------------------EXAMPLE 1---------------------'
  code: |-
    $proxy = Get-SPServiceApplicationProxy | ?{$_.TypeName -eq 'User Profile Service Application Proxy'}
    $security = Get-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy
    $everyone = New-SPClaimsPrincipal -Identity 'c:0(.s|true' -IdentityType EncodedClaim
    Revoke-SPObjectSecurity -Identity $security -Principal $everyone -Rights 'Create Personal Site'
    Set-SPProfileServiceApplicationSecurity -Identity $security -ProfileServiceApplicationProxy $proxy
  description: |-
    This example revokes the right 'Create Personal Site' from All Authenticated Users.
  summary: ""
- title: '--------------------EXAMPLE 2---------------------'
  code: |-
    $proxy = Get-SPServiceApplicationProxy | ?{$_.TypeName -eq 'User Profile Service Application Proxy'}
    $security = Get-SPProfileServiceApplicationSecurity -ProfileServiceApplicationProxy $proxy
    $everyone = New-SPClaimsPrincipal -Identity 'c:0(.s|true' -IdentityType EncodedClaim
    Grant-SPObjectSecurity -Identity $security -Principal $everyone -Rights 'All'
    Set-SPProfileServiceApplicationSecurity -Identity $security -ProfileServiceApplicationProxy $proxy
  description: |-
    This example grants the right 'All' to All Authenticated Users.
  summary: ""
parameters:
- type: <xref href="SPAssignmentCollection" data-throw-if-not-resolved="False" />
  name: AssignmentCollection
  description: |+
    Manages objects for the purpose of proper disposal. Use of objects, such as SPWeb or SPSite, can use large amounts of memory and use of these objects in Windows PowerShell scripts requires proper memory management. Using the SPAssignment object, you can assign objects to a variable and dispose of the objects after they are needed to free up memory. When SPWeb, SPSite, or SPSiteAdministration objects are used, the objects are automatically disposed of if an assignment collection or the Global parameter is not used.

    When the Global parameter is used, all objects are contained in the global store. If objects are not immediately used, or disposed of by using the Stop-SPAssignment command, an out-of-memory scenario can occur.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPObjectSecurity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    Specifies the User Profile Service Application security object.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPServiceApplicationProxyPipeBind" data-throw-if-not-resolved="False" />
  name: ProfileServiceApplicationProxy
  isRequired: true
  description: |+
    Specifies the unique identifier for the proxy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SPSiteSubscriptionPipeBind" data-throw-if-not-resolved="False" />
  name: SiteSubscription
  description: |+
    Specifies the account under which this service should run.
    This parameter is mandatory in a hosted-environment and optional in a non-hosted environment.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    Specifies the type of object to display.

    The type is any one of the following values:

    - MySiteReaderACL
    - UserACL

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Displays a message that describes the effect of the command instead of executing the command.
    For more information, type the following command: `get-help about_commonparameters`

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - SharePoint Server 2010
  - SharePoint Server 2013
  - SharePoint Server 2016
  - SharePoint Server 2019
  parameterValueGroup: ""
applicable:
- SharePoint Server 2010
- SharePoint Server 2013
- SharePoint Server 2016
- SharePoint Server 2019
uid: SharePointServer.Set-SPProfileServiceApplicationSecurity
name: Set-SPProfileServiceApplicationSecurity
description: |-
  Use the `Set-SPProfileServiceApplictionSecurity` cmdlet to set permission and identity information for the following User Profile objects:

  - Read individual My Sites
  - Use Personal Features
  - Use Social Features
  - Create Personal Site

  For permissions and the most current information about Windows PowerShell for SharePoint Products, see the online documentation at [SharePoint Server Cmdlets](https://learn.microsoft.com/powershell/sharepoint/sharepoint-server/sharepoint-server-cmdlets).
metadata:
  external help file: Microsoft.Office.Server.UserProfiles.dll-help.xml
  Module Name: Microsoft.SharePoint.Powershell
  online version: https://learn.microsoft.com/powershell/module/sharepoint-server/set-spprofileserviceapplicationsecurity
  applicable: SharePoint Server 2010, SharePoint Server 2013, SharePoint Server 2016, SharePoint Server 2019
  title: Set-SPProfileServiceApplicationSecurity
  schema: 2.0.0
  author: techwriter40
  ms.author: pamgreen
  ms.reviewer: ""
